### ISSUE TITLE
Add part attribute for styling from light DOM

### ISSUE THREAD

**Issue by Enes5519** [Trendyol/baklava#245]
**Is your feature request related to a problem? Please describe.**
I want to style from light DOM

**Describe the solution you'd like**
Add `part` attribute to some elements in components.

**Additional context**
[https://developer.mozilla.org/en-US/docs/Web/CSS/::part](https://developer.mozilla.org/en-US/docs/Web/CSS/::part)

**Comment by muratcorlu** [comment]
Which part do you want to style, and why?

**Comment by Enes5519** [comment]
Tooltip component for now. I want to change display property in `.trigger` and set width property to max-content in `.tooltip` .

**Comment by muratcorlu** [comment]
If there is a use case for customising those values, we can definitely consider defining some custom properties. `::part` is for allowing styling in "whatever you want" mode, but since we are providing a Design System here, we are trying to keep a consistent UI on and between our components. Maybe there will be really useful places for setting parts for some parts of our components, but I think it's not a good practice to define parts everywhere without a real need.

Can you define your use cases for changing `display` property for `.trigger` and `width` in `.tooltip`?

**Comment by Enes5519** [comment]
I open the PR. Thanks your comment. 👼
