### ISSUE TITLE
Bl-Input fixed width

### ISSUE THREAD

**Issue by olkeoguz** [Trendyol/baklava#246]
The Bl-Input component does not allow to set width where it was used. 

Consider Bl-Pagination as an example,  
In order to use the jumper in the figma link below, I need to be able use a different width then we provide in the input component. However I can't.

Figma : https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?node-id=118%3A4074

Of course the solution for this issue is by declaring the width variable in the "host" and allow users to change the width in a wrapper. 

Since similar issues may occur, I strongly recommend that we should reconsider which fields we need to allow users to change, since such situations may block our users from preferring us.

**Comment by muratcorlu** [comment]
This should just work, does not?:

```css
bl-input {
    width: 100px;
}
```

**Comment by olkeoguz** [comment]
Yes it works, but it is recommended to declare the customizable parts of o component in https://trendyol.github.io/baklava/?path=/docs/documentation-how-to-customize-a-components-style--page

Since the **width** is not a css custom property in the input element, the only way to change it is by overriding as you mentioned. 

So, is it right to override the non customizable properties here, or should we declare them as custom properties?

**Comment by muratcorlu** [comment]
Style of the host element of our components are already in light dom, so it's always possible to style them outside. In case of just setting the width of a fluid component, it's completely fine to set it with regular `width` css property. Basically it's not a "customizable part of the component". Our input is basically a fluid component with a default width of 200px. When we are talking about "customizing", we are talking about internal (technically speaking "shadowdom") of the components. If we would talk about setting color of the label of the input component, then a css custom property would be better for this since it's an internal element of the component and living inside shadowdom, and you can not style it directly.
