### ISSUE TITLE
bl-select's popover cannot be opened

### ISSUE THREAD

**Issue by olkeoguz** [Trendyol/baklava#252]
**Describe the bug**
When the bl-select component is used inside the render method of another baklava component, the popover is not opening where the options should be listed.

**To Reproduce**
1. Create a component.
2. Return the bl-select element with some options.
3. Click to open the dropdown.
4. The _isPopoverOpen state won't be set to true.

Demo:
https://codesandbox.io/s/litelement-forked-h5c55o?file=/src/index.js

**Expected behavior**
The popover should be opened and closed by clicking inside the component.

**Additional context**
The problem does not occur when the bl-select is used outside of shadowRoot of another component.(i.e: inside the html body).

For this reason,a quick fix can be done in the "_clickOutsideHandler" function of bl-select by changing it as:

```ts
 const target = event.target as HTMLElement;
    const containsTarget = target.tagName === 'BL-SELECT' ? target.contains(this) :
      target.shadowRoot?.querySelector('bl-select')?.contains(this);

    if (!containsTarget && this._isPopoverOpen) {
      this.close();
      this._checkRequired();
    }
```
 
@mustafafrw  @muratcorlu  what do you think?

**Comment by muratcorlu** [comment]
That's an interesting one! We use floating-ui for showing those popovers and apparently it can not manage to position something inside shadowdom (that seems make sense). Let's do some research on that.

**Comment by mustafafrw** [comment]
@muratcorlu Actually floating-ui seems to be very successful in managing position. The problem here seems to be caused by the `_clickOutsideHandler` function. This function closes the popover when we click somewhere outside of the popover. In this issue, handler function doesn't know if the element is clicked outside of it and always closes the popover. Because target element we get from the event is the custom element (in this example, it is test-element). We can find bl-select inside current `target`'s shadowRoot but there are some cases we should consider.

What if there are more than one `bl-select` elements inside the custom element?
What if bl-select is located in nested element?

**Comment by olkeoguz** [comment]
Yes, the `close` function gets triggered right after when the bl-select is `clicked to open` the popover.Because even if you click the inner element (bl-select), the target is pointing the parent element (test-element) and the following statement works:
 ```
if (!this.contains(target) && this._isPopoverOpen) {
      this.close();
    }
```

**Comment by muratcorlu** [comment]
So what is the current fix for that?

**Comment by mustafafrw** [comment]
`event.composedPath()` returns an array of invoked listeners. It should return shadow root elements as well. I think we can figure out this issue with it. 

If we change handler function like this, I expect it to resolve all cases.

    private _clickOutsideHandler = (event: MouseEvent) => {  
      if(!this._isPopoverOpen) return;  
      
      const eventPath = event.composedPath() as HTMLElement[];  
      
      if (!eventPath?.find(el => el.tagName === 'BL-SELECT')?.contains(this)) {  
	      this.close();  
	      this._checkRequired();  
	  }
    };

**Comment by muratcorlu** [comment]
@mustafafrw That looks good. But I noticed another potential risk about this. Currently we bind to document click event on connectedCallback to run this handler.

```ts
connectedCallback() {
    super.connectedCallback();

    document.addEventListener('click', this._clickOutsideHandler);
}
```

Instead we need to make this only when a popover is open. Otherwise on every document click, every select component in the page will run this handler.
