### ISSUE TITLE
Using checkbox component in form

### ISSUE THREAD

**Issue by muratcorlu** [Trendyol/baklava#291]
The checkbox component should be usable as a form input by implementing ElementInternals. We may also consider having a grouping component for using a checkbox as a form field. Like `checkbox-group` or `bl-fieldset` etc.

**Comment by olkeoguz** [comment]
I'm considering to make an implementation for this issue as below.

With the checkbox group component, we will also be dealing with #290.

## Implementation

General usage example:

```html 
  <bl-checkbox-group label="categories" name="categories">
         <bl-checkbox checked>sports</bl-checkbox>
         <bl-checkbox checked>casual</bl-checkbox>
         <bl-checkbox disabled>classics</bl-checkbox>
         <bl-checkbo>sports</bl-checkbox>
    </bl-checkbox-group>
```

## API Reference:

### `bl-checkbox-group` component

This component is the wrapper component for the group of checkboxes.` bl-checkbox `behavior will not change other than the implementation of element internals and the aria roles.

#### Attributes


| Attribute | Description | Default Value |
| --------- | ----------- | ------------- |
| label (`string`) | Label of the form field. This is needed for accessibility needs. | - |
| name (`string`) | Name of the form field | - |
| required (`boolean`) | Sets form field required | `false` |

#### Events

| Event | Description | Event Data |
| ----- | ----------- | ---------- |
| `bl-group-change` | Will be triggered in paralel with the bl-checkbox-change event fired in bl-checkbox  | array of checked checkbox values |

#### CSS Custom Properties

| Property | Description | Default Value |
| -------- | ----------- | ------------- |
| `--bl-checkbox-direction` | Can be used for showing checkboxes as columns instead of rows. Options are `row` or `column` | `row` |

**Comment by muratcorlu** [comment]
In this way, `bl-checkbox-group` should also have a `value` attribute. This attribute should always have the value of selected checkbox(es).

One thing that we need to consider is what will be the behavior if we both have `value` and some `checked` elements, like:

```html
<bl-checkbox-group label="Select categories" name="categories" value="sports,casual">
  <bl-checkbox value="sports">sports</bl-checkbox>
  <bl-checkbox value="casual">casual</bl-checkbox>
  <bl-checkbox value="classics" selected>classics</bl-checkbox>
</bl-checkbox-group>
```

In the [upcoming radio input component](#301), I considered this and removed `selected` attribute from `bl-radio` component since there was no use case to use `bl-radio` by itself (without `bl-radio-group`). But here the situation is a bit different, a checkbox can be used to enable/disable a single option. And also, there can be multiple selections here, so the value should handle to have multiple values.

We can check some other libraries for inspiration. Apparently, many libraries use checkbox components as form input (as native elements) not grouping element.

**Comment by olkeoguz** [comment]
Yes,I too haven't seen checbox group usage in a form a lot, but I think it brings a high user convenience for let's say a category selection in or out of form field. I believe It's not similar to select element since it does not have a dropdown or a search and it can be placed horizontally.

In the case you mentioned, we need to make the child and the group element listen each other on checkbox selections. 
I think we can do it with no problem at all but how about we take an array of options and put the` bl-checkbox` internally like below ? It seems a lot quicker to me:

```html
<bl-checkbox-group label="Select categories" name="categories">
</bl-checkbox-group>
```
```js
 checkboxGroup.options = [
      {
        value: "sports",
      },
     {
        value: "casual",
        disabled:true
      },
    ];

checkboxGroup.value = ["sports"]
```

**Comment by buseselvi** [comment]
Hi, we updated the checkbox design documentation here is [Figma link](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?node-id=606%3A4458&t=grn04SrLYL0DooLH-1). 

We added hover and focus states to the checkbox component as we did with the radio input component. Can we update it?

**Comment by muratcorlu** [comment]
> How about as a second option we take an array of options and put the` bl-checkbox` internally like we did in pagination ? It seems a lot quicker to me:
> 
> ```
> <bl-checkbox-group label="Select categories" name="categories">
> </bl-checkbox-group>
> ```
> 
>  
> ```js
>  checkboxGroup.options = [
>       {
>         value: "sports",
>       },
>      {
>         value: "casual",
>         disabled:true
>       },
>     ];
> 
> checkboxGroup.value = ["sports"]
> ```

Since we are creating custom elements here, we should try to keep components working declaratively. Being need to write some JS code to just show a basic checkbox selection should not be required. For some advanced customization setting properties via JS would be always an option but this should not be the first option. Using HTML for the "content" helps about many aspects like simplicity, flexibility, a11y, SSR etc.

There can be an hybrid solution like accepting both below:

```html
<form>
  ...
  <bl-checkbox name="accept_term" value="1" required>I accept <a href="#">terms and conditions</a></bl-checkbox>
  ..
</form>
```

In the example above, there is a single checkbox field and we can basically read it's `checked` value or the value of `accept_term` from the form element, since checkbox component will set this value on form element.

or

```html
<bl-checkbox-group label="Choose sports you like" name="sports" required>
  <bl-checkbox value="football">Football</bl-checkbox>
  <bl-checkbox value="basketball">Basketball</bl-checkbox>
  <bl-checkbox value="tennis">Tennis</bl-checkbox>
</bl-checkbox-group>
```

In this example, you don't need to repeat `name` attribute on every option. `group` component puts a label for multiple checkboxes, group them by setting same name.

For reading/setting value of a group, maybe we can use Lit's [attribute/property converters](https://lit.dev/docs/components/properties/#conversion-converter). In this case when you read it via JavaScript it may return an array and if read it from attribute then it may return a comma seperated string.

```html
<bl-checkbox-group id="sportSelection" label="Choose sports you like" name="sports" required value="basketball,tennis">
  <bl-checkbox value="football">Football</bl-checkbox>
  <bl-checkbox value="basketball">Basketball</bl-checkbox>
  <bl-checkbox value="tennis">Tennis</bl-checkbox>
</bl-checkbox-group>

<script>
  sportSelection.value; // ['basketball', 'tennis']
</script>
```
Or even we may consider to use a stringified JSON that is also [supported by Lit](https://lit.dev/docs/components/properties/#conversion-type), since it will be still not very complicated to just write a list of values. (`value='["basketball","tennis"]'`)

**Comment by olkeoguz** [comment]
Alright then, if this is settled, I'll implement both of these and compare the ease of usage. Thanks for a concrete explanation @muratcorlu.
