### ISSUE TITLE
BlProgressIndicator properties not working

### ISSUE THREAD

**Issue by AykutSarac** [Trendyol/baklava#295]
**Describe the bug**
BlProgressIndicator from npm package for React doesn't implement its properties like (size, failed etc.)

**Versions**
Baklava: v2.0.0-beta.38
React 18.2.0

**Additional context**
Works fine on web component (bl-progress-indicator)

**Comment by muratcorlu** [comment]
I confirm it doesn't work and the reason is we are using `size` and `failed` attributes in CSS selectors inside the component but since we don't reflect properties with attributes (with `@property({ ... , reflect: true })`) they are not present as attributes when it's set via property in React. Just adding `reflect: true` will fix the issue. I'll create a PR in a minute.
