### ISSUE TITLE
Dialog should focus on it's primary action button

### ISSUE THREAD

**Issue by muratcorlu** [Trendyol/baklava#406]
[We realized that](#395) currently dialog component moves focus to the close button when its open. Instead we expect it to focus on primary action, if present.

**Comment by muratcorlu** [comment]
In pull request #475, I included the "autofocus" feature for buttons. However, I am now questioning the practice of always focusing on the primary action in dialogs. This can pose a risk, particularly with confirmation dialogs, as it may cause users to inadvertently confirm something by pressing "Enter" twice. I believe that instead of automatically focusing on the primary action, we should provide the application developer/designer with the option to select the focused action, and even provide guidance on selecting the best action to focus on based on the given situation.

@buseselvi what do you think?

**Comment by buseselvi** [comment]
@muratcorlu It would be better to give a customizing initial focus option so that components such as input in the dialog can also be focused. By default, it may make sense to leave autofocus the same as it is (autofocus on the close button) to avoid misclicks as you mentioned. It can be changed to autofocus on the primary button or another component if wanted.

**Comment by muratcorlu** [comment]
Good point! It is important to note that dialog content may also require focus with an input. I'll try to add some examples to our Dialog component storybook to mention those possibilities.
