### ISSUE TITLE
Using Popover component in Dropdown Button

### ISSUE THREAD

**Issue by muratcorlu** [Trendyol/baklava#480]
Dropdown component should use Popover component in it to show action list

**Comment by ogunb** [comment]
There is a slight difference in behavior between the current dropdown popover and the popover component.

If we don't pass the "fit-size" attribute, the popover will size itself according to the content size. The current implementation has a minimum width of the button size.

However, when we do pass the "fit-size" attribute, the popover sets its width to be the same as its target, and the `bl-dropdown-item` will cut off the text with an ellipsis.

Short content without fit-size:
<img width="202" alt="Screenshot 2023-04-02 at 16 25 24" src="https://user-images.githubusercontent.com/24693913/229355669-74bb8a71-7532-4f55-8651-58b3220ec2b1.png">

Long content with fit-size:
<img width="201" alt="Screenshot 2023-04-02 at 16 24 32" src="https://user-images.githubusercontent.com/24693913/229355643-5f0f3065-55fc-48f6-bb5a-467a7fd3ca70.png">

Long content without fit-size:
<img width="279" alt="Screenshot 2023-04-02 at 16 25 42" src="https://user-images.githubusercontent.com/24693913/229355687-188996eb-a7f3-4ea5-acb8-f5b77b0e3598.png">

Long content and short text with fit-size:
<img width="118" alt="Screenshot 2023-04-02 at 17 18 01" src="https://user-images.githubusercontent.com/24693913/229358611-cf4a166f-bba1-4329-bc9e-55680e1853b2.png">

I have a couple of approaches listed, feel free to suggest new ones:

- We may change the implementation of the popover component by changing width to min-width. I am wary of this one since I personally haven't used it before.
- We may extend the implementation of "fit-size" prop by changing it to a string with options: width, min-width, max-width. And defaulting to width.
- We may add a "fit-size" prop to the dropdown component, allowing users to make the decision themselves.
- We may ignore the issue and leave it as is; functionally, nothing will change, but the behavior will be obviously different.

[Draft](https://github.com/Trendyol/baklava/pull/510)

**Comment by muratcorlu** [comment]
Good catch. Since our expected behaviour is as in dropdown component (it’s also same in Select component) popover `fit-size` should work as `min-width`, I think. Adding a custom value for this attribute can be considered in the future, once we need it (as your 2nd suggestion). I’m not sure if its possible to use an attribute as both `boolean` and as a `string` at the same time though. If so, `<bl-popover fit-size>` will use `min-width`, `<bl-popover fit-size=“width”>` will use `width`. I didn’t check but I assume this would be possible.
