### ISSUE TITLE
Drawer has delay for removing from dom 

### ISSUE THREAD

**Issue by ozkersemih** [Trendyol/baklava#536]
**Description**
When user closes drawer, there is 1000ms delay for animation. This also causes delay for removing operation from dom. We can solve it with check animation ended or not with more suitable method.

**Expected behavior**
We should not use timeout when we remove component from dom. We should check with function.
**Screenshots**
![image](https://user-images.githubusercontent.com/52029025/233093477-c0cbf1cf-845b-4b0e-afef-1bf867a34b73.png)
**Desktop (please complete the following information):**

**Comment by muratcorlu** [comment]
Maybe it's better to mention what problem that causes: If the user opens a drawer with an `embed-url` (so with an iframe) and navigate in iframe, then close drawer and open it again in 1 seconds, drawer opens with the previous state (same url in iframe as left) instead of initial url of the iframe.

So, basically, the main problem is not the timeout (because we put it for waiting the slide-out animation) but this affects iframe navigation inside.

Let's consider this bug in this context.
