### ISSUE TITLE
The padding of the dialog content should be set to 0

### ISSUE THREAD

**Issue by Enes5519** [Trendyol/baklava#600]
If the dialog has an action container, the content container of the dialog should have a padding of 0. Otherwise, the gap between actions and content is too great.

**Actual**:
<img width="615" alt="image" src="https://github.com/Trendyol/baklava/assets/10272532/12d662f8-187c-4a04-94ea-807f42c45615">

**Expect**:
<img width="559" alt="image" src="https://github.com/Trendyol/baklava/assets/10272532/bc4700ca-6691-45b5-b261-ef7a83029c59">

**Comment by muratcorlu** [comment]
@buseselvi can you comment about this?

**Comment by buseselvi** [comment]
Good point! Since there is padding at the top of the footer where the buttons are located, the two paddings together lose some space. So we may not give any padding to the bottom of the content. 

But of course, in the case where the button footer is not used on the dialog component, still, there should be a 24 px padding from the bottom. @muratcorlu @Enes5519
