### ISSUE TITLE
itemsPerPageOptions is not included in bl-pagination storybook documentation.

### ISSUE THREAD

**Issue by MehmetCanBOZ** [Trendyol/baklava#673]
I used the **bl-pagination** component and needed a custom options list. But I couldn't see any property for the custom options list in the documentation. Then I saw an attribute called itemsPerPageOptions in [bl-pagination's code file](https://github.com/Trendyol/baklava/blob/next/src/components/pagination/bl-pagination.ts). This attribute is not included in the documentation. Is there a special reason for this or could it be that the attribute was forgotten to be added?

1 -  Go to https://baklava.design/?path=/docs/components-pagination--documentation#customization 
2 - There is a custom option list in the example.
3 - But in the Reference section, there is no property named itemsPerPageOptions for the custom options list for this component.

**Comment by muratcorlu** [comment]
Since `itemsPerPageOptions` is a property that you can not set as an HTML attribute (which is always string), unfortuantely it's not automatically documented in storybook. But I think we would have a proper code example in "Customization" section to cover this use-case. JS codes in the stories are not visible. But we could write a code sample like we did in some other places[^1][^2]. A PR would be very welcome.

[^1]: https://baklava.design/?path=/docs/components-input--documentation#using-within-a-form
[^2]: https://baklava.design/?path=/docs/components-select-select--documentation#using-as-form-input
