### ISSUE TITLE
[Feature Request]: I should be able to choose the color for the bl-badge used in the bl-tab

### ISSUE THREAD

**Issue by sametkabay** [Trendyol/baklava#736]
### Describe the problem or use case

<img width="1018" alt="Screenshot 2023-10-31 at 18 28 11" src="https://github.com/Trendyol/baklava/assets/19507324/564cca47-6bdc-4b18-9b49-4c7f4dad9e78">

When I use badge in a tab as in the image, I can only decide on the text inside the badge.  I should be able to choose different colors (like: #FFEEEB, ...) or types (like: Approved, Warning, Denied) for the badge.

### Proposed solution

`<bl-tab name="test-1" slot="tabs" badge="New">Tab 1</bl-tab>`

New attribute can be added: badge-color:"xxx" or badge-type: "xxx"

**Comment by leventozen** [comment]
Hi @sametkabay, Thank you for bringing up this point. We understand that you're looking to customize the color of the badge within a tab component. You can indeed achieve this customization by using the [current capabilities of Baklava](https://baklava.design/?path=/docs/documentation-customizing-components-style--documentation), without the need for additional attributes.

Here's how you can customize the badge color within a tab component:
```html
<style>
  .wrapper {
    --bl-badge-bg-color: red;
    --bl-badge-color: white;
  }
</style>

<bl-tab-group>
  <bl-tab class="wrapper" name="test-1" slot="tabs" badge="New">Tab 1</bl-tab>
  <bl-tab name="test-2" slot="tabs">Tab 2</bl-tab>
  <bl-tab name="test-3" slot="tabs" disabled badge="New">Tab 3</bl-tab>
</bl-tab-group>
```
By defining a wrapper class and applying CSS custom properties, you can influence the appearance of the badge while respecting the boundaries set by the design system.

We appreciate your understanding that, in order to maintain the consistency and principles of Baklava, we currently have no plans to introduce additional attributes for direct customization of badge colors or types within the framework. However, we hope this solution meets your needs while staying within the design constraints of Baklava.

Please don't hesitate to reach out if you have further questions or need additional guidance.

**Comment by sametkabay** [comment]
Hi @leventozen, your suggestion sounds good. I can use it this way, thank you.
